name: Publish Maven package
on:
  workflow_dispatch:
jobs:
  publish_maven:
    name: Publish package to the Maven Central Repository
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Java/Object Validator'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Publish package
        run: |
          ./gradlew clean
          ./gradlew publish
          ./gradlew jreleaserDeploy
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          MAVEN_TOKEN_USERNAME: ${{ secrets.MAVEN_TOKEN_USERNAME }}
          MAVEN_TOKEN_PASSWORD: ${{ secrets.MAVEN_TOKEN_PASSWORD }}